services:
  postgres:
    image: postgres:15-alpine
    container_name: trackspring-postgres
    environment:
      POSTGRES_DB: trackspring_db
      POSTGRES_USER: trackspring_user
      POSTGRES_PASSWORD: trackspring_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trackspring_user -d trackspring_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trackspring-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/trackspring_db
      - SPRING_DATASOURCE_USERNAME=trackspring_user
      - SPRING_DATASOURCE_PASSWORD=trackspring_password
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trackspring-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
